buymyjunk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import login_view, logout_view, register_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace='items')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import all_items_view, item_detail_view, delete_item_view

app_name = 'items'


urlpatterns = [
    # path('', index_view, name='home'),
    # path('items/', ItemsListView.as_view(), name='list'),
    path('', all_items_view, name='list'),
    # path('items/<pk>', ItemDetailView.as_view(), name='details'),
    path('items/<int:pk>', item_detail_view, name='details'),
    path('<int:pk>/delete', delete_item_view, name='delete'),
]

messaging/urls.py
from django.urls import path
from .views import messagebox_view#MsgBoxView

app_name = 'messaging'

urlpatterns = [
    # path('', MsgBoxView.as_view(), name='messagebox')
    path('', messagebox_view, name='messagebox')
]

messaging/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Thread(models.Model):
    subject = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name='threads', related_query_name='thread')
    subject = models.CharField(max_length=120, null=True)

    @property
    def get_users(self):
        return list(self.users.all())

    @property
    def messages(self):
        return Message.objects.filter(thread=self)

    def __str__(self):
        parties = self.get_users
        return f"Conversation between users {' and '.join([p.username for p in parties])}"


# TODO: Should I move subject to Thread?
class Message(models.Model):
    sender =models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='sender')
    recipient = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='recipient')
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE) 
    content = models.TextField(max_length=500)
    # unread = models.BinaryField(default=True) # This should not be at this level, needs to be user specific.
    sent_at = models.DateTimeField(auto_now_add=True)
    # readable_by = models.ManyToManyField(User) # This should 
    # TODO: Think about what should happen when the foreign keys are deleted!
    # def save(self, thread=None, subject=None):
    #     if thread is None:
    #         thread = Thread.objects.create(subject=subject)
    #         thread.users.add(self.sender, self.recipient)
    #         thread.save()
    #     self.thread = thread
    #     super().save()

    def mark_as_read(self):
        self.unread = False

    def mark_as_unread(self):
        self.unread = True
    
    def __str__(self):
        return f'Message from {self.sender.username} to {self.recipient.username} on {self.sent_at}'
    
    

messaging/forms.py
from django import forms
from .models import Message, Thread

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        # exclude = ('thread', 'sender', 'recipient')
        fields = ('content',)

    def print_data(self):
        print(self.cleaned_data)

class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ('subject',)

messaging/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from .models import Message, Thread
from .forms import MessageForm

# Create your views here.

@login_required
def messagebox_view(req):
    user = req.user
    inbox = Thread.objects.filter(users__in=[user]).all()
    # ReplyFormSet = inlineformset_factory(Thread, Message, form=MessageForm, extra=len(inbox))
    # threads_w_forms = []
    # for thread in inbox:
    #     threads_w_forms.append([thread, ReplyFormSet(req.POST,instance=thread)])
# TODO: The validation below is not correct. Think how to do it properly.
    msg_form = MessageForm(data=req.POST or None)
    active_thread = inbox[0]
    if req.method == 'POST':
        if msg_form.is_valid():
            message = message_form.save(commit=False)
            message.thread = thread
            reply = reply_form.save()
    context = {
        'username': user.username,
        'inbox': inbox,
        'active_thread': inbox[0] or None
        # 'reply_forms': reply_forms,
    }
    return render(req, 'messaging/messagebox.html', context)


# class MsgBoxView(ListView, LoginRequiredMixin):
#     template_name = 'messaging/messagebox.html'
#     model = Message

# def message_box_view(req):
#     return render(req, 'messaging/messagebox.html')

messaging/templates/messaging/message_modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="reportModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="messageModalLabel">Message {{object.seller.user}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="report-modal">
                <div id="result-box"></div>
                    <form id="message-form" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{thread_form|crispy}}
                        {{message_form|crispy}}
                        <button type="submit" class="btn btn-info mt-2">Send</button>
                    </form>
            </div>
        <!---div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div-->
        </div>
    </div>
</div>

messaging/templates/messaging/messagebox.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Message Box
{% endblock title %}


{% block content %}
    <h1>Your conversations</h1>
    {% if not inbox %}
        <p>You currently don't have any conversations.</p>
    {% else %}
        {% for thread in inbox %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-out-{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse-out-{{forloop.counter}}">
                        {{thread.0.subject}} between {% if thread.0.get_users.1.username == username %}you {% else %}{{thread.0.get_users.1}}{% endif %} and {% if thread.0.get_users.0.username == username %}you {% else %}{{thread.0.get_users.0}}{% endif %}
                    </button>
                </h2>
                <div id="flush-collapse-out-{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="row">
                            {% for msg in thread.0.message_set.all %}
                                <div class="col">
                                    <div class="card">
                                        <div class="card-body">
                                            {{msg.content}}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <button class="btn btn-primary col-1" data-bs-toggle="collapse" target="#reply-{{thread.id}}">Reply</button>
                        <button class="btn btn-danger  col-1" type="submit">Delete</button>
                        <form id="reply-{{thread.0.id}}" method="POST" action="" class="col" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{thread.1|crispy}}
                            <button type="submit" class="btn btn-info mt-2">Send</button>
                        </form>
                        <form method="POST" class="col-1">
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% comment %} {% for msg in inbox %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-out-{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse-out-{{forloop.counter}}">
                        Conversation between {{ msg.get_users.0 }} and {{ msg.get_users.1 }}. Last message {{msg.updated_at|timesince}} ago.
                    </button>
                </h2>
                <div id="flush-collapse-out-{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <div class="row"><b>{{ msg.subject }}</b></div>
                        <div class="row">{{msg.content}}</div>
                        <div class="row">
                            <button class="btn btn-primary col-1">Reply</button>
                            <form method="POST" class="col-1">
                                {% csrf_token %}
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %} {% endcomment %}
    {% endif %}
    {% comment %} <h1>Outbox</h1>
    {% for msg in outbox %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-out-{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse-out-{{forloop.counter}}">
                    Message to {{msg.recipient}} sent {{msg.sent_at|timesince}} ago.
                </button>
            </h2>
            <div id="flush-collapse-out-{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <div class="row"><b>{{ msg.subject }}</b></div>
                    <div class="row">{{msg.content}}</div>
                    <div class="row">
                        <button class="btn btn-primary col-1">Reply</button>
                        <form method="POST" class="col-1">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %} {% endcomment %}
    <!--ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Inbox</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Outbox</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% if not inbox %}
                <h4>You have no incoming messages</h4>
            {% endif %}
            <div class="accordion accordion-flush" id="outbox-messages">
                {% for msg in inbox %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-out-{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse-out-{{forloop.counter}}">
                                Message from {{msg.sender}} sent {{msg.sent_at|timesince}} ago.
                            </button>
                        </h2>
                        <div id="flush-collapse-out-{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                <div class="row">{{msg.content}}</div>
                                <div class="row col-md-3">
                                    <button class="btn btn-primary col-2">Reply</button>
                                    <form method="POST" class="col-2">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            {% if not outbox %}
                <h4>You have no outgoing messages</h4>
            {% endif %}
            <div class="accordion accordion-flush" id="outbox-messages">
                {% for msg in outbox %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-out-{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapse-out-{{forloop.counter}}">
                                Message to {{msg.recipient}} sent {{msg.sent_at|timesince}} ago.
                            </button>
                        </h2>
                        <div id="flush-collapse-out-{{forloop.counter}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <div class="accordion-body">
                                <div class="row">{{msg.content}}</div>
                                <div class="row">
                                    <button class="btn btn-primary col-1">Reply</button>
                                    <form method="POST" class="col-1">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </-->
{% endblock content %}