buymyjunk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import login_view, logout_view, register_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace='items')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('messaging/', include('messaging.urls', namespace='messaging')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import all_items_view, item_detail_view, delete_item_view

app_name = 'items'


urlpatterns = [
    # path('', index_view, name='home'),
    # path('items/', ItemsListView.as_view(), name='list'),
    path('', all_items_view, name='list'),
    # path('items/<pk>', ItemDetailView.as_view(), name='details'),
    path('items/<int:pk>', item_detail_view, name='details'),
    path('<int:pk>/delete', delete_item_view, name='delete'),
]

messaging/urls.py
from django.urls import path
from .views import messagebox_view#MsgBoxView

app_name = 'messaging'

urlpatterns = [
    # path('', MsgBoxView.as_view(), name='messagebox')
    path('', messagebox_view, name='messagebox')
]

profiles/urls.py
from django.urls import path
from .views import profile_view, all_profiles_view#, update_profile_view

app_name = 'profiles'

urlpatterns = [
    path('', all_profiles_view, name='allprofs'),
    # path('update/', update_profile_view, name='update'),
    path('<pk>', profile_view, name='profile'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Buy and Sell Second Hand | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% for msg in messages %}
    {% if msg.level_tag == 'error' %}
      <div class="text-center alert alert-danger" role="alert">
    {% else %}
      <div class="text-center alert alert-{{msg.level_tag}}" role="alert">
    {% endif %}
          {{msg.message}}
      </div>
    {% endfor %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/navbar.html
{% load static %}
{% url 'items:list' as path_to_home %}
{% url 'reports:main' as path_to_reports %}
{% url 'messaging:messagebox' as path_to_messagebox %}
{% url 'items:list' as path_to_items %}
{% url 'profiles:profile' request.user.profile.id as path_to_own_profile %}
{% url 'logout' as path_to_logout %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><img src="{% static 'favicon.ico' %}" class="logo-sm"></a>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_home %}active{% endif %}" href={{path_to_home}}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if path_to_items in request.path|truncatechars:8 %}active{% endif %}" href="{{path_to_items}}">Browse Items</a>
        </li>
        <!--li class="nav-item">
          <a class="nav-link {% if request.path == path_to_upload %}active{% endif %}" href="{{path_to_upload}}">Post an Item</a>
        </li-->
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_messagebox %}active{% endif %}" href="{{path_to_messagebox}}">Messages</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
      <div class="nav-item dropdown">
        <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <img src={{request.user.profile.avatar.url}} class="avatar-sm">&nbsp;{{request.user}}
        </div>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="{{ path_to_own_profile }}">Profile</a></li>
          <li><a class="dropdown-item" href="{{ path_to_logout }}">Logout</a></li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>